title: Python
description: Apprendre le Python avec Lucas !

# theme: just-the-docs # use localyy
remote_theme: pmarsceill/just-the-docs # use on github

url: https://rodolphebarbanneau.github.io/python

aux_links:
  Download: https://www.python.org/
