# See: https://jekyllrb.com/docs/configuration/
title: Python w/ Lucas
description: Apprendre le Python avec Lucas !
url: https://rodolphebarbanneau.github.io/python

# Build settings
color_scheme: dark
remote_theme: pmarsceill/just-the-docs # use on github
# theme: just-the-docs # use localyy

# Auxiliary links
aux_links:
  Python w/ Lucas on GitHub: https://github.com/rodolphebarbanneau/python

# External navigation links
nav_external_links:
  - title: Python
    url: https://www.python.org/
    hide_icon: false
